print("Let's do a Mad Lib!")
one = input("give a verb: ")
two = input("give an adjective; ")
three = input("give a plural noun: ")
four = input("give an adjective: ")
five = input("give a verb ending in \"ing\": ")
six = input("give a verb: ")
seven = input("give a number: ")
eight = input("give an adjective: ")
nine = input("give a plural noun: ")
ten = input("give another plural noun: ")
eleven = input("give a plural noun: ")
twelve = input("give a plural relative of yours: ")
thirteen = input("give an adjective: ")
fourteen = input("give another adjective: ")
fifteen = input("give a pural noun: ")

print("\nCome",one,"at WALMART, where you`ll\n receive", two, "discounts on all of your\n favorite brand name",three+".", "Our\n", four,"and",five,"associates are there to\n",six, "you",seven,"hours a day. Here you will find\n",eight, "prices on the",nine, "you need.", ten,"for\n the moms,",eleven,"for the kids and all the\n latest electronics for the",twelve+". So come\n on down to your", thirteen,fourteen, "WALMART\n where the",fifteen,"come first.")